
import { Deal, Company } from './types.ts';

export const SEED_COMPANIES: Company[] = [
  // ... Existing companies ...
  { id: 'c1', name: 'Rio Tinto', sector: 'Mining & Metals', headquarters: 'London, UK', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/6/66/Rio_Tinto_Group_logo.svg' },
  { id: 'c2', name: 'Arcadium Lithium', sector: 'Mining & Metals', headquarters: 'Shannon, Ireland', logo_url: 'https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://arcadiumlithium.com&size=128' },
  { id: 'c3', name: 'Alimentation Couche-Tard', sector: 'Retail', headquarters: 'Laval, Canada', logo_url: 'https://upload.wikimedia.org/wikipedia/en/2/23/Alimentation_Couche-Tard_Logo.svg' },
  { id: 'c4', name: 'Seven & i Holdings', sector: 'Retail', headquarters: 'Tokyo, Japan', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/2/26/Seven_%26_i_Holdings_logo.svg' },
  { id: 'c5', name: 'Blackstone', sector: 'Private Equity', headquarters: 'New York, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/b/b8/Blackstone_New_Logo.svg' },
  { id: 'c6', name: 'AirTrunk', sector: 'Data Infrastructure', headquarters: 'Sydney, Australia', logo_url: 'https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://airtrunk.com&size=128' },
  { id: 'c7', name: 'Salesforce', sector: 'Software', headquarters: 'San Francisco, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/f/f9/Salesforce.com_logo.svg' },
  { id: 'c8', name: 'Own Company', sector: 'Software', headquarters: 'Englewood Cliffs, USA', logo_url: 'https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://owndata.com&size=128' },
  { id: 'c9', name: 'Verizon', sector: 'Telecommunications', headquarters: 'New York, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/8/86/Verizon_logo_2024.svg' },
  { id: 'c10', name: 'Frontier Communications', sector: 'Telecommunications', headquarters: 'Norwalk, USA', logo_url: 'https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://frontier.com&size=128' },
  { id: 'c11', name: 'Mars, Incorporated', sector: 'Consumer Goods', headquarters: 'McLean, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Mars_Inc_logo.svg' },
  { id: 'c12', name: 'Kellanova', sector: 'Consumer Goods', headquarters: 'Chicago, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Kellanova_Logo.svg' },
  { id: 'c13', name: 'AMD', sector: 'Technology', headquarters: 'Santa Clara, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/7/7c/AMD_Logo.svg' },
  { id: 'c14', name: 'ZT Systems', sector: 'Hardware', headquarters: 'Secaucus, USA', logo_url: 'https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://ztsystems.com&size=128' },
  { id: 'c15', name: 'T-Mobile US', sector: 'Telecommunications', headquarters: 'Bellevue, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/a/ae/T-Mobile_logo_2022.svg' },
  { id: 'c16', name: 'UScellular', sector: 'Telecommunications', headquarters: 'Chicago, USA', logo_url: 'https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://uscellular.com&size=128' },
  // New Companies for expanded dataset
  { id: 'c17', name: 'Microsoft', sector: 'Technology', headquarters: 'Redmond, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg' },
  { id: 'c18', name: 'Activision Blizzard', sector: 'Technology', headquarters: 'Santa Monica, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Activision_Blizzard_Logo_2023.svg' },
  { id: 'c19', name: 'Broadcom', sector: 'Technology', headquarters: 'San Jose, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/c/cb/Broadcom_Inc._Logo.svg' },
  { id: 'c20', name: 'VMware', sector: 'Technology', headquarters: 'Palo Alto, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/9/9a/Vmware.svg' },
  { id: 'c21', name: 'ExxonMobil', sector: 'Energy', headquarters: 'Spring, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/5/54/Exxon_Mobil_Logo.svg' },
  { id: 'c22', name: 'Pioneer Natural Resources', sector: 'Energy', headquarters: 'Irving, USA', logo_url: '' },
  { id: 'c23', name: 'Chevron', sector: 'Energy', headquarters: 'San Ramon, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/4/41/Chevron_Logo.svg' },
  { id: 'c24', name: 'Hess Corporation', sector: 'Energy', headquarters: 'New York, USA', logo_url: '' },
  { id: 'c25', name: 'Cisco', sector: 'Technology', headquarters: 'San Jose, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/0/08/Cisco_logo_blue_2016.svg' },
  { id: 'c26', name: 'Splunk', sector: 'Technology', headquarters: 'San Francisco, USA', logo_url: '' },
  { id: 'c27', name: 'Capital One', sector: 'Financial Services', headquarters: 'McLean, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/9/98/Capital_One_logo.svg' },
  { id: 'c28', name: 'Discover Financial', sector: 'Financial Services', headquarters: 'Riverwoods, USA', logo_url: '' },
  { id: 'c29', name: 'Synopsys', sector: 'Technology', headquarters: 'Sunnyvale, USA', logo_url: '' },
  { id: 'c30', name: 'Ansys', sector: 'Technology', headquarters: 'Canonsburg, USA', logo_url: '' },
  { id: 'c31', name: 'HPE', sector: 'Technology', headquarters: 'Spring, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/4/48/Hewlett_Packard_Enterprise_logo.svg' },
  { id: 'c32', name: 'Juniper Networks', sector: 'Technology', headquarters: 'Sunnyvale, USA', logo_url: '' },
  { id: 'c33', name: 'Adobe', sector: 'Technology', headquarters: 'San Jose, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/8/8d/Adobe_Corporate_Logo.png' },
  { id: 'c34', name: 'Figma', sector: 'Technology', headquarters: 'San Francisco, USA', logo_url: '' },
  { id: 'c35', name: 'Kroger', sector: 'Retail', headquarters: 'Cincinnati, USA', logo_url: '' },
  { id: 'c36', name: 'Albertsons', sector: 'Retail', headquarters: 'Boise, USA', logo_url: '' },
  { id: 'c37', name: 'Johnson & Johnson', sector: 'Healthcare', headquarters: 'New Brunswick, USA', logo_url: '' },
  { id: 'c38', name: 'Shockwave Medical', sector: 'Healthcare', headquarters: 'Santa Clara, USA', logo_url: '' },
  { id: 'c39', name: 'Home Depot', sector: 'Retail', headquarters: 'Atlanta, USA', logo_url: '' },
  { id: 'c40', name: 'SRS Distribution', sector: 'Industrial', headquarters: 'McKinney, USA', logo_url: '' },
  { id: 'c41', name: 'ConocoPhillips', sector: 'Energy', headquarters: 'Houston, USA', logo_url: '' },
  { id: 'c42', name: 'Marathon Oil', sector: 'Energy', headquarters: 'Houston, USA', logo_url: '' },
  { id: 'c43', name: 'Diamondback Energy', sector: 'Energy', headquarters: 'Midland, USA', logo_url: '' },
  { id: 'c44', name: 'Endeavor Energy', sector: 'Energy', headquarters: 'Midland, USA', logo_url: '' },
  { id: 'c45', name: 'BlackRock', sector: 'Financial Services', headquarters: 'New York, USA', logo_url: '' },
  { id: 'c46', name: 'Global Infrastructure Partners', sector: 'Financial Services', headquarters: 'New York, USA', logo_url: '' },
  { id: 'c47', name: 'Renesas Electronics', sector: 'Technology', headquarters: 'Tokyo, Japan', logo_url: '' },
  { id: 'c48', name: 'Altium', sector: 'Technology', headquarters: 'San Diego, USA', logo_url: '' },
  { id: 'c49', name: 'Truist Financial', sector: 'Financial Services', headquarters: 'Charlotte, USA', logo_url: '' },
  { id: 'c50', name: 'Stone Point Capital', sector: 'Private Equity', headquarters: 'Greenwich, USA', logo_url: '' },
  { id: 'c51', name: 'Walmart', sector: 'Retail', headquarters: 'Bentonville, USA', logo_url: '' },
  { id: 'c52', name: 'Vizio', sector: 'Consumer Electronics', headquarters: 'Irvine, USA', logo_url: '' },
  { id: 'c53', name: 'IBM', sector: 'Technology', headquarters: 'Armonk, USA', logo_url: '' },
  { id: 'c54', name: 'HashiCorp', sector: 'Technology', headquarters: 'San Francisco, USA', logo_url: '' },
  { id: 'c55', name: 'Nippon Steel', sector: 'Industrial', headquarters: 'Tokyo, Japan', logo_url: '' },
  { id: 'c56', name: 'U.S. Steel', sector: 'Industrial', headquarters: 'Pittsburgh, USA', logo_url: '' },
  { id: 'c57', name: 'Pfizer', sector: 'Healthcare', headquarters: 'New York, USA', logo_url: '' },
  { id: 'c58', name: 'Seagen', sector: 'Healthcare', headquarters: 'Bothell, USA', logo_url: '' },
  { id: 'c59', name: 'Amgen', sector: 'Healthcare', headquarters: 'Thousand Oaks, USA', logo_url: '' },
  { id: 'c60', name: 'Horizon Therapeutics', sector: 'Healthcare', headquarters: 'Dublin, Ireland', logo_url: '' },
  { id: 'c61', name: 'Bunge', sector: 'Agriculture', headquarters: 'St. Louis, USA', logo_url: '' },
  { id: 'c62', name: 'Viterra', sector: 'Agriculture', headquarters: 'Rotterdam, Netherlands', logo_url: '' },
  { id: 'c63', name: 'Smurfit Kappa', sector: 'Industrial', headquarters: 'Dublin, Ireland', logo_url: '' },
  { id: 'c64', name: 'WestRock', sector: 'Industrial', headquarters: 'Atlanta, USA', logo_url: '' },
  { id: 'c65', name: 'Novo Nordisk', sector: 'Healthcare', headquarters: 'Bagsværd, Denmark', logo_url: '' },
  { id: 'c66', name: 'Catalent', sector: 'Healthcare', headquarters: 'Somerset, USA', logo_url: '' },
  { id: 'c67', name: 'Silver Lake', sector: 'Private Equity', headquarters: 'Menlo Park, USA', logo_url: '' },
  { id: 'c68', name: 'Endeavor', sector: 'Entertainment', headquarters: 'Beverly Hills, USA', logo_url: '' },
  { id: 'c69', name: 'Thoma Bravo', sector: 'Private Equity', headquarters: 'Chicago, USA', logo_url: '' },
  { id: 'c70', name: 'Darktrace', sector: 'Technology', headquarters: 'Cambridge, UK', logo_url: '' },
  { id: 'c71', name: 'EQT', sector: 'Private Equity', headquarters: 'Stockholm, Sweden', logo_url: '' },
  { id: 'c72', name: 'Keywords Studios', sector: 'Technology', headquarters: 'Dublin, Ireland', logo_url: '' },
  { id: 'c73', name: 'BBVA', sector: 'Financial Services', headquarters: 'Bilbao, Spain', logo_url: '' },
  { id: 'c74', name: 'Sabadell', sector: 'Financial Services', headquarters: 'Alicante, Spain', logo_url: '' },
  { id: 'c75', name: 'Sony', sector: 'Entertainment', headquarters: 'Tokyo, Japan', logo_url: '' },
  { id: 'c76', name: 'Paramount Global', sector: 'Entertainment', headquarters: 'New York, USA', logo_url: '' },
  { id: 'c77', name: 'Skydance Media', sector: 'Entertainment', headquarters: 'Santa Monica, USA', logo_url: '' },
  { id: 'c78', name: 'Alphabet (Google)', sector: 'Technology', headquarters: 'Mountain View, USA', logo_url: '' },
  { id: 'c79', name: 'HubSpot', sector: 'Technology', headquarters: 'Cambridge, USA', logo_url: '' },
  { id: 'c80', name: 'Squarespace', sector: 'Technology', headquarters: 'New York, USA', logo_url: '' },
  { id: 'c81', name: 'Permira', sector: 'Private Equity', headquarters: 'London, UK', logo_url: '' },
];

export const SEED_DEALS: Deal[] = [
  // ... Existing 8 deals from previous step ...
  {
    id: 'd1',
    slug: 'rio-tinto-arcadium-acquisition',
    title: 'Rio Tinto to Acquire Arcadium Lithium',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2024-10-09',
    expected_close: 'Mid 2025',
    value_usd: 6700000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Mining giant Rio Tinto has agreed to acquire Arcadium Lithium in an all-cash transaction.',
    sector: 'Mining & Metals',
    geography: 'Global',
    acquirer_id: 'c1',
    target_id: 'c2',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd2',
    slug: 'couche-tard-seven-i-bid',
    title: 'Couche-Tard Bid for Seven & i',
    status: 'Rumored',
    visibility: 'public',
    announced_date: '2024-10-09',
    expected_close: 'TBD 2025',
    value_usd: 47000000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Alimentation Couche-Tard has reportedly increased its offer to acquire Seven & i Holdings.',
    sector: 'Retail',
    geography: 'Asia / Global',
    acquirer_id: 'c3',
    target_id: 'c4',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd3',
    slug: 'blackstone-airtrunk-acquisition',
    title: 'Blackstone to Acquire AirTrunk',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2024-09-04',
    expected_close: '2025',
    value_usd: 16100000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Blackstone and CPP Investments have agreed to acquire Australian data center operator AirTrunk.',
    sector: 'Data Infrastructure',
    geography: 'APAC',
    acquirer_id: 'c5',
    target_id: 'c6',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd4',
    slug: 'verizon-frontier-acquisition',
    title: 'Verizon to Acquire Frontier',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2024-09-05',
    expected_close: 'Mid 2026',
    value_usd: 20000000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Verizon will acquire Frontier Communications in an all-cash transaction to expand its fiber footprint.',
    sector: 'Telecommunications',
    geography: 'North America',
    acquirer_id: 'c9',
    target_id: 'c10',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd5',
    slug: 'salesforce-own-acquisition',
    title: 'Salesforce to Acquire Own Company',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2024-09-05',
    expected_close: 'Q4 2024',
    value_usd: 1900000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Salesforce has agreed to acquire Own Company, a leading provider of data protection.',
    sector: 'Software',
    geography: 'North America',
    acquirer_id: 'c7',
    target_id: 'c8',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd6',
    slug: 'mars-kellanova-acquisition',
    title: 'Mars to Acquire Kellanova',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2024-08-14',
    expected_close: 'H1 2025',
    value_usd: 35900000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Mars, Incorporated has entered into a definitive agreement to acquire Kellanova.',
    sector: 'Consumer Goods / Food',
    geography: 'Global',
    acquirer_id: 'c11',
    target_id: 'c12',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd7',
    slug: 'amd-zt-systems-acquisition',
    title: 'AMD to Acquire ZT Systems',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2024-08-19',
    expected_close: 'H1 2025',
    value_usd: 4900000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'AMD plans to acquire ZT Systems to accelerate AI infrastructure strategy.',
    sector: 'Technology / Hardware',
    geography: 'North America',
    acquirer_id: 'c13',
    target_id: 'c14',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd8',
    slug: 't-mobile-uscellular-acquisition',
    title: 'T-Mobile to Acquire UScellular Ops',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2024-05-28',
    expected_close: 'Mid 2025',
    value_usd: 4400000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'T-Mobile US will acquire substantially all of UScellular\'s wireless operations.',
    sector: 'Telecommunications',
    geography: 'North America',
    acquirer_id: 'c15',
    target_id: 'c16',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  // --- NEW MAJOR DEALS ---
  {
    id: 'd9',
    slug: 'microsoft-activision',
    title: 'Microsoft Acquires Activision Blizzard',
    status: 'Completed',
    visibility: 'public',
    announced_date: '2022-01-18',
    expected_close: 'Completed',
    value_usd: 68700000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Microsoft has completed its acquisition of Activision Blizzard, the largest deal in gaming history.',
    sector: 'Technology / Gaming',
    geography: 'North America',
    acquirer_id: 'c17',
    target_id: 'c18',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd10',
    slug: 'broadcom-vmware',
    title: 'Broadcom Acquires VMware',
    status: 'Completed',
    visibility: 'public',
    announced_date: '2022-05-26',
    expected_close: 'Completed',
    value_usd: 69000000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Semiconductor giant Broadcom has completed its acquisition of VMware to diversify into enterprise software.',
    sector: 'Technology',
    geography: 'North America',
    acquirer_id: 'c19',
    target_id: 'c20',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd11',
    slug: 'exxon-pioneer',
    title: 'ExxonMobil Acquires Pioneer',
    status: 'Completed',
    visibility: 'public',
    announced_date: '2023-10-11',
    expected_close: 'Completed',
    value_usd: 59500000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'ExxonMobil acquires Pioneer Natural Resources, doubling its footprint in the Permian Basin.',
    sector: 'Energy',
    geography: 'North America',
    acquirer_id: 'c21',
    target_id: 'c22',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd12',
    slug: 'chevron-hess',
    title: 'Chevron to Acquire Hess',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2023-10-23',
    expected_close: '2025',
    value_usd: 53000000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Chevron agrees to buy Hess Corporation to gain a foothold in Guyana\'s oil fields.',
    sector: 'Energy',
    geography: 'Global',
    acquirer_id: 'c23',
    target_id: 'c24',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd13',
    slug: 'cisco-splunk',
    title: 'Cisco Acquires Splunk',
    status: 'Completed',
    visibility: 'public',
    announced_date: '2023-09-21',
    expected_close: 'Completed',
    value_usd: 28000000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Cisco acquires cybersecurity and observability leader Splunk to bolster its software portfolio.',
    sector: 'Technology',
    geography: 'North America',
    acquirer_id: 'c25',
    target_id: 'c26',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd14',
    slug: 'capitalone-discover',
    title: 'Capital One to Acquire Discover',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2024-02-19',
    expected_close: '2025',
    value_usd: 35300000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Capital One plans to acquire Discover Financial Services, creating a credit card giant.',
    sector: 'Financial Services',
    geography: 'North America',
    acquirer_id: 'c27',
    target_id: 'c28',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd15',
    slug: 'synopsys-ansys',
    title: 'Synopsys to Acquire Ansys',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2024-01-16',
    expected_close: 'H1 2025',
    value_usd: 35000000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Synopsys agrees to buy engineering software firm Ansys to create a leader in silicon to systems design.',
    sector: 'Technology',
    geography: 'North America',
    acquirer_id: 'c29',
    target_id: 'c30',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd16',
    slug: 'hpe-juniper',
    title: 'HPE to Acquire Juniper Networks',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2024-01-09',
    expected_close: 'Late 2024',
    value_usd: 14000000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'HPE to acquire Juniper Networks to accelerate its AI-driven networking strategy.',
    sector: 'Technology',
    geography: 'North America',
    acquirer_id: 'c31',
    target_id: 'c32',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd17',
    slug: 'adobe-figma',
    title: 'Adobe Acquisition of Figma',
    status: 'Withdrawn',
    visibility: 'public',
    announced_date: '2022-09-15',
    expected_close: 'Cancelled',
    value_usd: 20000000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Adobe and Figma mutually agreed to terminate their merger agreement due to regulatory hurdles.',
    sector: 'Technology',
    geography: 'North America',
    acquirer_id: 'c33',
    target_id: 'c34',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd18',
    slug: 'kroger-albertsons',
    title: 'Kroger to Acquire Albertsons',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2022-10-14',
    expected_close: '2025',
    value_usd: 24600000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Kroger and Albertsons plan to merge to compete with Walmart, facing intense FTC scrutiny.',
    sector: 'Retail',
    geography: 'North America',
    acquirer_id: 'c35',
    target_id: 'c36',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd19',
    slug: 'jnj-shockwave',
    title: 'J&J Acquires Shockwave Medical',
    status: 'Completed',
    visibility: 'public',
    announced_date: '2024-04-05',
    expected_close: 'Completed',
    value_usd: 13100000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Johnson & Johnson strengthens its MedTech cardiovascular portfolio with Shockwave acquisition.',
    sector: 'Healthcare',
    geography: 'North America',
    acquirer_id: 'c37',
    target_id: 'c38',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd20',
    slug: 'homedepot-srs',
    title: 'Home Depot Acquires SRS Distribution',
    status: 'Completed',
    visibility: 'public',
    announced_date: '2024-03-28',
    expected_close: 'Completed',
    value_usd: 18250000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Home Depot acquires SRS Distribution to expand its reach in the professional contractor market.',
    sector: 'Retail / Industrial',
    geography: 'North America',
    acquirer_id: 'c39',
    target_id: 'c40',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd21',
    slug: 'conocophillips-marathon',
    title: 'ConocoPhillips to Acquire Marathon Oil',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2024-05-29',
    expected_close: 'Q4 2024',
    value_usd: 22500000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'ConocoPhillips expands its US shale footprint with the acquisition of Marathon Oil.',
    sector: 'Energy',
    geography: 'North America',
    acquirer_id: 'c41',
    target_id: 'c42',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd22',
    slug: 'diamondback-endeavor',
    title: 'Diamondback Acquires Endeavor Energy',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2024-02-12',
    expected_close: 'Q4 2024',
    value_usd: 26000000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Diamondback Energy merges with Endeavor Energy Resources to create a Permian giant.',
    sector: 'Energy',
    geography: 'North America',
    acquirer_id: 'c43',
    target_id: 'c44',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd23',
    slug: 'blackrock-gip',
    title: 'BlackRock to Acquire GIP',
    status: 'Completed',
    visibility: 'public',
    announced_date: '2024-01-12',
    expected_close: 'Completed',
    value_usd: 12500000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'BlackRock acquires Global Infrastructure Partners, betting big on infrastructure investing.',
    sector: 'Financial Services',
    geography: 'Global',
    acquirer_id: 'c45',
    target_id: 'c46',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd24',
    slug: 'renesas-altium',
    title: 'Renesas to Acquire Altium',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2024-02-14',
    expected_close: '2024',
    value_usd: 5900000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Japanese chipmaker Renesas to buy software firm Altium to streamline electronics design.',
    sector: 'Technology',
    geography: 'APAC / Global',
    acquirer_id: 'c47',
    target_id: 'c48',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd25',
    slug: 'truist-insurance',
    title: 'Truist Sells Insurance Stake',
    status: 'Completed',
    visibility: 'public',
    announced_date: '2024-02-20',
    expected_close: 'Completed',
    value_usd: 15500000000,
    currency: 'USD',
    percent_acquired: 80,
    synopsis: 'Truist Financial sells a majority stake in its insurance brokerage to Stone Point Capital and CD&R.',
    sector: 'Financial Services',
    geography: 'North America',
    acquirer_id: 'c50',
    target_id: 'c49',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd26',
    slug: 'walmart-vizio',
    title: 'Walmart to Acquire Vizio',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2024-02-20',
    expected_close: '2025',
    value_usd: 2300000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Walmart agrees to buy TV maker Vizio to boost its advertising business.',
    sector: 'Retail / Tech',
    geography: 'North America',
    acquirer_id: 'c51',
    target_id: 'c52',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd27',
    slug: 'ibm-hashicorp',
    title: 'IBM to Acquire HashiCorp',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2024-04-24',
    expected_close: 'Late 2024',
    value_usd: 6400000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'IBM to acquire cloud software company HashiCorp to expand its hybrid cloud capabilities.',
    sector: 'Technology',
    geography: 'North America',
    acquirer_id: 'c53',
    target_id: 'c54',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd28',
    slug: 'nippon-ussteel',
    title: 'Nippon Steel to Acquire U.S. Steel',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2023-12-18',
    expected_close: 'TBD',
    value_usd: 14900000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Nippon Steel\'s bid for U.S. Steel faces significant political opposition in the US.',
    sector: 'Industrial',
    geography: 'Global',
    acquirer_id: 'c55',
    target_id: 'c56',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd29',
    slug: 'pfizer-seagen',
    title: 'Pfizer Acquires Seagen',
    status: 'Completed',
    visibility: 'public',
    announced_date: '2023-03-13',
    expected_close: 'Completed',
    value_usd: 43000000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Pfizer completes acquisition of Seagen, doubling down on oncology therapies.',
    sector: 'Healthcare',
    geography: 'North America',
    acquirer_id: 'c57',
    target_id: 'c58',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd30',
    slug: 'amgen-horizon',
    title: 'Amgen Acquires Horizon',
    status: 'Completed',
    visibility: 'public',
    announced_date: '2022-12-12',
    expected_close: 'Completed',
    value_usd: 27800000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Amgen closes acquisition of Horizon Therapeutics following FTC settlement.',
    sector: 'Healthcare',
    geography: 'Global',
    acquirer_id: 'c59',
    target_id: 'c60',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd31',
    slug: 'bunge-viterra',
    title: 'Bunge to Merge with Viterra',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2023-06-13',
    expected_close: 'Mid 2025',
    value_usd: 8200000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Bunge and Viterra to merge, creating a global agribusiness giant to rival ADM and Cargill.',
    sector: 'Agriculture',
    geography: 'Global',
    acquirer_id: 'c61',
    target_id: 'c62',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd32',
    slug: 'smurfit-westrock',
    title: 'Smurfit Kappa Merges with WestRock',
    status: 'Completed',
    visibility: 'public',
    announced_date: '2023-09-12',
    expected_close: 'Completed',
    value_usd: 11200000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Smurfit Kappa and WestRock combine to create Smurfit Westrock, a global packaging leader.',
    sector: 'Industrial',
    geography: 'Global',
    acquirer_id: 'c63',
    target_id: 'c64',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd33',
    slug: 'novo-catalent',
    title: 'Novo Holdings to Acquire Catalent',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2024-02-05',
    expected_close: 'Late 2024',
    value_usd: 16500000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Novo Holdings to acquire contract manufacturer Catalent to boost Wegovy supply.',
    sector: 'Healthcare',
    geography: 'Global',
    acquirer_id: 'c65',
    target_id: 'c66',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd34',
    slug: 'silverlake-endeavor',
    title: 'Silver Lake Takes Endeavor Private',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2024-04-02',
    expected_close: 'Q1 2025',
    value_usd: 13000000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Silver Lake to acquire Endeavor Group Holdings, taking the entertainment giant private.',
    sector: 'Entertainment',
    geography: 'North America',
    acquirer_id: 'c67',
    target_id: 'c68',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd35',
    slug: 'thomabravo-darktrace',
    title: 'Thoma Bravo Acquires Darktrace',
    status: 'Completed',
    visibility: 'public',
    announced_date: '2024-04-26',
    expected_close: 'Completed',
    value_usd: 5300000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Thoma Bravo takes UK cybersecurity firm Darktrace private.',
    sector: 'Technology',
    geography: 'Europe',
    acquirer_id: 'c69',
    target_id: 'c70',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd36',
    slug: 'eqt-keywords',
    title: 'EQT to Acquire Keywords Studios',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2024-07-03',
    expected_close: 'Late 2024',
    value_usd: 2800000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'EQT agrees to buy Keywords Studios, a major service provider to the video game industry.',
    sector: 'Technology / Gaming',
    geography: 'Europe',
    acquirer_id: 'c71',
    target_id: 'c72',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd37',
    slug: 'bbva-sabadell',
    title: 'BBVA Hostile Bid for Sabadell',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2024-04-30',
    expected_close: '2025',
    value_usd: 12400000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'BBVA launches hostile takeover bid for smaller Spanish rival Sabadell.',
    sector: 'Financial Services',
    geography: 'Europe',
    acquirer_id: 'c73',
    target_id: 'c74',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd38',
    slug: 'skydance-paramount',
    title: 'Skydance to Merge with Paramount',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2024-07-07',
    expected_close: 'H1 2025',
    value_usd: 8000000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Skydance Media agrees to merge with Paramount Global ending a dramatic bidding war.',
    sector: 'Entertainment',
    geography: 'North America',
    acquirer_id: 'c77',
    target_id: 'c76',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd39',
    slug: 'google-hubspot-rumor',
    title: 'Google Considering HubSpot Bid',
    status: 'Rumored',
    visibility: 'public',
    announced_date: '2024-04-04',
    expected_close: 'TBD',
    value_usd: 35000000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Alphabet reportedly weighing an offer for HubSpot, though regulatory risks remain high.',
    sector: 'Technology',
    geography: 'North America',
    acquirer_id: 'c78',
    target_id: 'c79',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd40',
    slug: 'permira-squarespace',
    title: 'Permira Takes Squarespace Private',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2024-05-13',
    expected_close: 'Late 2024',
    value_usd: 6900000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Permira agrees to take website building platform Squarespace private.',
    sector: 'Technology',
    geography: 'North America',
    acquirer_id: 'c81',
    target_id: 'c80',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd41',
    slug: 'sony-paramount-bid',
    title: 'Sony & Apollo Bid for Paramount',
    status: 'Withdrawn',
    visibility: 'public',
    announced_date: '2024-05-02',
    expected_close: 'Cancelled',
    value_usd: 26000000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Sony and Apollo Global Management expressed interest in Paramount before withdrawing.',
    sector: 'Entertainment',
    geography: 'North America',
    acquirer_id: 'c75',
    target_id: 'c76',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  }
];
