
import { Deal, Company } from './types.ts';

export const SEED_COMPANIES: Company[] = [
  { id: 'c1', name: 'Mars, Incorporated', sector: 'Consumer Goods', headquarters: 'McLean, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Mars_Inc_logo.svg' },
  { id: 'c2', name: 'Kellanova', sector: 'Consumer Goods', headquarters: 'Chicago, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Kellanova_Logo.svg' },
  { id: 'c3', name: 'Synopsys', sector: 'Technology', headquarters: 'Sunnyvale, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/0/00/Synopsys_Logo.svg' },
  { id: 'c4', name: 'Ansys', sector: 'Technology', headquarters: 'Canonsburg, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/e/e8/Ansys_logo.svg' },
  { id: 'c5', name: 'Capital One', sector: 'Financial Services', headquarters: 'McLean, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/9/98/Capital_One_logo.svg' },
  { id: 'c6', name: 'Discover Financial', sector: 'Financial Services', headquarters: 'Riverwoods, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/5/58/Discover_Card_logo.svg' },
  { id: 'c7', name: 'Hewlett Packard Enterprise', sector: 'Technology', headquarters: 'Spring, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/4/46/Hewlett_Packard_Enterprise_logo.svg' },
  { id: 'c8', name: 'Juniper Networks', sector: 'Technology', headquarters: 'Sunnyvale, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/9/90/Juniper_Networks_logo.svg' },
  { id: 'c9', name: 'Verizon', sector: 'Telecommunications', headquarters: 'New York, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/8/86/Verizon_logo_2024.svg' },
  { id: 'c10', name: 'Frontier Communications', sector: 'Telecommunications', headquarters: 'Norwalk, USA', logo_url: 'https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://frontier.com&size=128' },
  { id: 'c11', name: 'BlackRock', sector: 'Financial Services', headquarters: 'New York, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/0/07/BlackRock_wordmark.svg' },
  { id: 'c12', name: 'Global Infrastructure Partners', sector: 'Private Equity', headquarters: 'New York, USA', logo_url: 'https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://global-infra.com&size=128' },
  { id: 'c13', name: 'Johnson & Johnson', sector: 'Pharmaceuticals', headquarters: 'New Brunswick, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/b/be/J%26J_Logo_New.svg' },
  { id: 'c14', name: 'Shockwave Medical', sector: 'Medical Devices', headquarters: 'Santa Clara, USA', logo_url: 'https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://shockwavemedical.com&size=128' },
  { id: 'c15', name: 'IBM', sector: 'Technology', headquarters: 'Armonk, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/5/51/IBM_logo.svg' },
  { id: 'c16', name: 'HashiCorp', sector: 'Software', headquarters: 'San Francisco, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/7/7b/HashiCorp_Horizontal_Logo.svg' },
  { id: 'c17', name: 'AMD', sector: 'Technology', headquarters: 'Santa Clara, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/7/7c/AMD_Logo.svg' },
  { id: 'c18', name: 'ZT Systems', sector: 'Hardware', headquarters: 'Secaucus, USA', logo_url: 'https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://ztsystems.com&size=128' },
  { id: 'c19', name: 'Diamondback Energy', sector: 'Energy', headquarters: 'Midland, USA', logo_url: 'https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://diamondbackenergy.com&size=128' },
  { id: 'c20', name: 'Endeavor Energy', sector: 'Energy', headquarters: 'Midland, USA', logo_url: 'https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://endeavourenergyltd.com&size=128' },
];

export const SEED_DEALS: Deal[] = [
  {
    id: 'd1',
    slug: 'mars-kellanova-acquisition',
    title: 'Mars to Acquire Kellanova for $35.9 Billion',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2024-08-14',
    value_usd: 35900000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Mars, Incorporated has entered into a definitive agreement to acquire Kellanova (formerly Kellogg) for $83.50 per share in cash, creating a global snacking giant.',
    rationale: 'The deal expands Mars\' snacking portfolio into savory categories (Pringles, Cheez-It) and strengthens its international distribution footprint.',
    sector: 'Consumer Goods / Food',
    geography: 'Global',
    acquirer_id: 'c1',
    target_id: 'c2',
    // Mars is private, no ticker response
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd2',
    slug: 'synopsys-ansys-acquisition',
    title: 'Synopsys to Acquire Ansys for $35 Billion',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2024-01-16',
    value_usd: 35000000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Synopsys will acquire Ansys in a cash-and-stock deal, uniting leader in semiconductor design with leader in simulation software.',
    rationale: 'Creates a silicon-to-systems design solutions leader, essential for the era of AI and software-defined systems.',
    sector: 'Technology / Software',
    geography: 'North America',
    acquirer_id: 'c3',
    target_id: 'c4',
    market_response: {
      acquirer_ticker: 'SNPS',
      change_percent: 3.1,
      sentiment_summary: 'Investors reacted positively to the strategic fit despite the high premium.'
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd3',
    slug: 'capitalone-discover-merger',
    title: 'Capital One to Acquire Discover for $35.3 Billion',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2024-02-19',
    value_usd: 35300000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Capital One Financial has agreed to acquire Discover Financial Services in an all-stock transaction valued at $35.3 billion.',
    rationale: 'The merger would create the largest US credit card issuer by loan volume and give Capital One its own payments network to compete with Visa/Mastercard.',
    sector: 'Financial Services',
    geography: 'North America',
    acquirer_id: 'c5',
    target_id: 'c6',
    market_response: {
      acquirer_ticker: 'COF',
      change_percent: -3.6,
      sentiment_summary: 'Stock fell on regulatory antitrust concerns, though analysts see long-term synergy.'
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd4',
    slug: 'hpe-juniper-acquisition',
    title: 'HPE to Acquire Juniper Networks for $14 Billion',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2024-01-09',
    value_usd: 14000000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Hewlett Packard Enterprise will acquire Juniper Networks for $40.00 per share in an all-cash transaction.',
    rationale: 'Accelerates HPE’s pivot to high-growth networking business and doubles its networking business scope, driven by AI infrastructure demand.',
    sector: 'Technology / Infrastructure',
    geography: 'North America',
    acquirer_id: 'c7',
    target_id: 'c8',
    market_response: {
      acquirer_ticker: 'HPE',
      change_percent: -8.9,
      sentiment_summary: 'Market skeptics sold off shares citing potential integration risks and debt load.'
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd5',
    slug: 'verizon-frontier-acquisition',
    title: 'Verizon to Acquire Frontier Communications for $20 Billion',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2024-09-05',
    value_usd: 20000000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Verizon will acquire Frontier Communications in an all-cash transaction to expand its fiber footprint across the US.',
    rationale: 'Significantly expands Verizon’s fiber network to compete with AT&T and cable providers in key markets.',
    sector: 'Telecommunications',
    geography: 'North America',
    acquirer_id: 'c9',
    target_id: 'c10',
    market_response: {
      acquirer_ticker: 'VZ',
      change_percent: -0.4,
      sentiment_summary: 'Muted reaction; analysts view it as a defensive necessity but question the valuation.'
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd6',
    slug: 'blackrock-gip-acquisition',
    title: 'BlackRock Acquires Global Infrastructure Partners for $12.5 Billion',
    status: 'Completed',
    visibility: 'public',
    announced_date: '2024-01-12',
    value_usd: 12500000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'BlackRock acquires GIP, the world’s largest independent infrastructure manager, adding over $100 billion in client assets.',
    rationale: 'Infrastructure is projected to be one of the fastest growing asset classes; this deal positions BlackRock as the market leader.',
    sector: 'Financial Services',
    geography: 'Global',
    acquirer_id: 'c11',
    target_id: 'c12',
    market_response: {
      acquirer_ticker: 'BLK',
      change_percent: 0.8,
      sentiment_summary: 'Positive sentiment on diversifying revenue streams beyond passive index funds.'
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd7',
    slug: 'jnj-shockwave-acquisition',
    title: 'Johnson & Johnson Acquires Shockwave Medical for $13.1 Billion',
    status: 'Completed',
    visibility: 'public',
    announced_date: '2024-04-05',
    value_usd: 13100000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Johnson & Johnson MedTech completes acquisition of Shockwave, a pioneer in intravascular lithotripsy for treating calcified cardiovascular disease.',
    rationale: 'Strengthens J&J’s cardiovascular portfolio, adding a high-growth platform in the interventional cardiology space.',
    sector: 'Medical Devices',
    geography: 'North America',
    acquirer_id: 'c13',
    target_id: 'c14',
    market_response: {
      acquirer_ticker: 'JNJ',
      change_percent: -0.1,
      sentiment_summary: 'Neutral reaction; seen as a sound strategic tuck-in but fully priced.'
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd8',
    slug: 'ibm-hashicorp-acquisition',
    title: 'IBM to Acquire HashiCorp for $6.4 Billion',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2024-04-24',
    value_usd: 6400000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'IBM has agreed to acquire HashiCorp for $35 per share in cash to accelerate its hybrid cloud automation capabilities.',
    rationale: 'HashiCorp’s Terraform is the industry standard for infrastructure-as-code; this fits perfectly into IBM’s Red Hat strategy.',
    sector: 'Technology / Cloud',
    geography: 'North America',
    acquirer_id: 'c15',
    target_id: 'c16',
    market_response: {
      acquirer_ticker: 'IBM',
      change_percent: -8.0,
      sentiment_summary: 'Investors questioned the premium paid for a company with slowing growth rates.'
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd9',
    slug: 'amd-zt-systems-acquisition',
    title: 'AMD to Acquire ZT Systems for $4.9 Billion',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2024-08-19',
    value_usd: 4900000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'AMD plans to acquire ZT Systems, a leading provider of AI infrastructure for hyperscalers.',
    rationale: 'This is a vertical integration play to accelerate the deployment of AMD’s AI accelerators in data centers, similar to Nvidia’s strategy.',
    sector: 'Technology / Hardware',
    geography: 'North America',
    acquirer_id: 'c17',
    target_id: 'c18',
    market_response: {
      acquirer_ticker: 'AMD',
      change_percent: 4.5,
      sentiment_summary: 'Strong approval; analysts see this closing the time-to-market gap with Nvidia.'
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd10',
    slug: 'diamondback-endeavor-merger',
    title: 'Diamondback Energy Merges with Endeavor Energy for $26 Billion',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2024-02-12',
    value_usd: 26000000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Diamondback Energy and Endeavor Energy Resources have agreed to merge to create a premier Permian Basin independent operator.',
    rationale: 'Consolidation in the Permian Basin to achieve scale and operational efficiencies in US oil production.',
    sector: 'Energy',
    geography: 'North America',
    acquirer_id: 'c19',
    target_id: 'c20',
    market_response: {
      acquirer_ticker: 'FANG',
      change_percent: 9.4,
      sentiment_summary: 'Market cheered the deal as a "best-in-class" combination of Permian assets.'
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  }
];
