
import { Deal, Company } from './types.ts';

export const SEED_COMPANIES: Company[] = [
  { id: 'c1', name: 'Rio Tinto', sector: 'Mining & Metals', headquarters: 'London, UK', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/6/66/Rio_Tinto_Group_logo.svg' },
  { id: 'c2', name: 'Arcadium Lithium', sector: 'Mining & Metals', headquarters: 'Shannon, Ireland', logo_url: 'https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://arcadiumlithium.com&size=128' },
  { id: 'c3', name: 'Alimentation Couche-Tard', sector: 'Retail', headquarters: 'Laval, Canada', logo_url: 'https://upload.wikimedia.org/wikipedia/en/2/23/Alimentation_Couche-Tard_Logo.svg' },
  { id: 'c4', name: 'Seven & i Holdings', sector: 'Retail', headquarters: 'Tokyo, Japan', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/2/26/Seven_%26_i_Holdings_logo.svg' },
  { id: 'c5', name: 'Blackstone', sector: 'Private Equity', headquarters: 'New York, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/b/b8/Blackstone_New_Logo.svg' },
  { id: 'c6', name: 'AirTrunk', sector: 'Data Infrastructure', headquarters: 'Sydney, Australia', logo_url: 'https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://airtrunk.com&size=128' },
  { id: 'c7', name: 'Salesforce', sector: 'Software', headquarters: 'San Francisco, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/f/f9/Salesforce.com_logo.svg' },
  { id: 'c8', name: 'Own Company', sector: 'Software', headquarters: 'Englewood Cliffs, USA', logo_url: 'https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://owndata.com&size=128' },
  { id: 'c9', name: 'Verizon', sector: 'Telecommunications', headquarters: 'New York, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/8/86/Verizon_logo_2024.svg' },
  { id: 'c10', name: 'Frontier Communications', sector: 'Telecommunications', headquarters: 'Norwalk, USA', logo_url: 'https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://frontier.com&size=128' },
  { id: 'c11', name: 'Mars, Incorporated', sector: 'Consumer Goods', headquarters: 'McLean, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Mars_Inc_logo.svg' },
  { id: 'c12', name: 'Kellanova', sector: 'Consumer Goods', headquarters: 'Chicago, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Kellanova_Logo.svg' },
  { id: 'c13', name: 'AMD', sector: 'Technology', headquarters: 'Santa Clara, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/7/7c/AMD_Logo.svg' },
  { id: 'c14', name: 'ZT Systems', sector: 'Hardware', headquarters: 'Secaucus, USA', logo_url: 'https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://ztsystems.com&size=128' },
  { id: 'c15', name: 'T-Mobile US', sector: 'Telecommunications', headquarters: 'Bellevue, USA', logo_url: 'https://upload.wikimedia.org/wikipedia/commons/a/ae/T-Mobile_logo_2022.svg' },
  { id: 'c16', name: 'UScellular', sector: 'Telecommunications', headquarters: 'Chicago, USA', logo_url: 'https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://uscellular.com&size=128' },
];

export const SEED_DEALS: Deal[] = [
  {
    id: 'd1',
    slug: 'rio-tinto-arcadium-acquisition',
    title: 'Rio Tinto to Acquire Arcadium Lithium for $6.7 Billion',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2024-10-09',
    expected_close: 'Mid 2025',
    value_usd: 6700000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Mining giant Rio Tinto has agreed to acquire Arcadium Lithium in an all-cash transaction at $5.85 per share, representing a 90% premium to Arcadium\'s closing price.',
    rationale: 'The acquisition positions Rio Tinto as a top-three global lithium producer, securing essential supply for the electric vehicle transition during a market dip in lithium prices.',
    sector: 'Mining & Metals',
    geography: 'Global',
    acquirer_id: 'c1',
    target_id: 'c2',
    market_response: {
      acquirer_ticker: 'RIO',
      change_percent: -0.85,
      sentiment_summary: 'Investors showed mild skepticism on timing given depressed lithium prices, but acknowledged the long-term strategic necessity.'
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd2',
    slug: 'couche-tard-seven-i-bid',
    title: 'Couche-Tard Increases Bid for Seven & i to $47 Billion',
    status: 'Rumored',
    visibility: 'public',
    announced_date: '2024-10-09',
    expected_close: 'TBD 2025',
    value_usd: 47000000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Alimentation Couche-Tard has reportedly increased its offer to acquire Seven & i Holdings to ¥7 trillion ($47 billion) in an attempt to bring the Japanese retailer to the negotiating table.',
    rationale: 'A merger would create the world\'s premier convenience store operator with over 100,000 locations, combining Circle K and 7-Eleven brands.',
    sector: 'Retail',
    geography: 'Asia / Global',
    acquirer_id: 'c3',
    target_id: 'c4',
    market_response: {
      acquirer_ticker: 'ATD',
      change_percent: 4.5,
      sentiment_summary: 'Market reacted positively to the aggressive pursuit of scale despite the hostile nature of the bid.'
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd3',
    slug: 'blackstone-airtrunk-acquisition',
    title: 'Blackstone to Acquire AirTrunk for $16 Billion',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2024-09-04',
    expected_close: '2025',
    value_usd: 16100000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Blackstone and CPP Investments have agreed to acquire Australian data center operator AirTrunk in the largest-ever investment in Asia Pacific digital infrastructure.',
    rationale: 'The deal underscores the massive capital requirements of the AI boom, securing Blackstone a dominant position in APAC cloud infrastructure.',
    sector: 'Data Infrastructure',
    geography: 'APAC',
    acquirer_id: 'c5',
    target_id: 'c6',
    market_response: {
      acquirer_ticker: 'BX',
      change_percent: 1.2,
      sentiment_summary: 'Consistent with Blackstone\'s thematic deployment into AI and data centers; received well by analysts.'
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd4',
    slug: 'verizon-frontier-acquisition',
    title: 'Verizon to Acquire Frontier Communications for $20 Billion',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2024-09-05',
    expected_close: 'Mid 2026',
    value_usd: 20000000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Verizon will acquire Frontier Communications in an all-cash transaction to expand its fiber footprint across the US, targeting closing in 18 months.',
    rationale: 'Significantly expands Verizon’s fiber network to compete with AT&T and cable providers in key markets, adding 2.2 million fiber subscribers.',
    sector: 'Telecommunications',
    geography: 'North America',
    acquirer_id: 'c9',
    target_id: 'c10',
    market_response: {
      acquirer_ticker: 'VZ',
      change_percent: -0.4,
      sentiment_summary: 'Muted reaction; analysts view it as a defensive necessity but question the integration timeline (2026).'
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd5',
    slug: 'salesforce-own-acquisition',
    title: 'Salesforce to Acquire Own Company for $1.9 Billion',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2024-09-05',
    expected_close: 'Q4 2024',
    value_usd: 1900000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Salesforce has agreed to acquire Own Company, a leading provider of data protection and data management solutions, for $1.9 billion in cash.',
    rationale: 'Strengthens Salesforce\'s data security posture, a critical layer for enterprise AI adoption and platform resilience.',
    sector: 'Software',
    geography: 'North America',
    acquirer_id: 'c7',
    target_id: 'c8',
    market_response: {
      acquirer_ticker: 'CRM',
      change_percent: 0.5,
      sentiment_summary: 'Seen as a smart, low-risk bolt-on of a long-time ecosystem partner.'
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd6',
    slug: 'mars-kellanova-acquisition',
    title: 'Mars to Acquire Kellanova for $35.9 Billion',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2024-08-14',
    expected_close: 'H1 2025',
    value_usd: 35900000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'Mars, Incorporated has entered into a definitive agreement to acquire Kellanova (formerly Kellogg) for $83.50 per share in cash, creating a global snacking giant.',
    rationale: 'The deal expands Mars\' snacking portfolio into savory categories (Pringles, Cheez-It) and strengthens its international distribution footprint.',
    sector: 'Consumer Goods / Food',
    geography: 'Global',
    acquirer_id: 'c11',
    target_id: 'c12',
    // Mars is private
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd7',
    slug: 'amd-zt-systems-acquisition',
    title: 'AMD to Acquire ZT Systems for $4.9 Billion',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2024-08-19',
    expected_close: 'H1 2025',
    value_usd: 4900000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'AMD plans to acquire ZT Systems, a leading provider of AI infrastructure for hyperscalers.',
    rationale: 'This is a vertical integration play to accelerate the deployment of AMD’s AI accelerators in data centers, similar to Nvidia’s strategy.',
    sector: 'Technology / Hardware',
    geography: 'North America',
    acquirer_id: 'c13',
    target_id: 'c14',
    market_response: {
      acquirer_ticker: 'AMD',
      change_percent: 4.5,
      sentiment_summary: 'Strong approval; analysts see this closing the time-to-market gap with Nvidia.'
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: 'd8',
    slug: 't-mobile-uscellular-acquisition',
    title: 'T-Mobile to Acquire UScellular Operations for $4.4 Billion',
    status: 'Pending',
    visibility: 'public',
    announced_date: '2024-05-28',
    expected_close: 'Mid 2025',
    value_usd: 4400000000,
    currency: 'USD',
    percent_acquired: 100,
    synopsis: 'T-Mobile US will acquire substantially all of UScellular\'s wireless operations, including customers and stores, as well as certain spectrum assets.',
    rationale: 'Consolidates the US wireless market further and improves T-Mobile\'s coverage in rural areas where UScellular has a strong foothold.',
    sector: 'Telecommunications',
    geography: 'North America',
    acquirer_id: 'c15',
    target_id: 'c16',
    market_response: {
      acquirer_ticker: 'TMUS',
      change_percent: 0.9,
      sentiment_summary: 'Positive; deal structure allows T-Mobile to acquire subscribers without taking on all debt.'
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  }
];
